export const SIGN_IN = "SIGN_IN"
export const LOGOUT = "LOGOUT"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
export const CHECK_AUTH = "CHECK_AUTH"

export const GET_MENUS = "GET_MENU"
export const ADD_MENU = "ADD_MENU"
export const MENU_NOTIFY = "MENU_NOTIFY"
export const MENUS = "MENUS"